# Generated by Django 5.0.7 on 2024-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("name",), "verbose_name_plural": "Dishes"},
        ),
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="dishes",
                to="service.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True
            ),
        ),
    ]
