# Generated by Django 5.0.7 on 2024-08-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_dish_options_alter_dish_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="dishes", to="service.ingredient"
            ),
        ),
    ]
