# Generated by Django 5.0.7 on 2024-08-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_dish_ingredients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ("dish_type", "name"),
                "verbose_name_plural": "Dishes",
            },
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ("id",)},
        ),
    ]
