# Generated by Django 5.0.7 on 2024-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_cook_options_alter_dish_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
